# Generated by Django 3.1.1 on 2021-07-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend18', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateDb',
            new_name='CreateDb18',
        ),
    ]
