# Generated by Django 3.1.1 on 2021-02-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend25', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdb',
            name='comment_one',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Коммент 1'),
        ),
        migrations.AddField(
            model_name='createdb',
            name='comment_two',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Коммент 2'),
        ),
    ]
