# Generated by Django 3.1.1 on 2020-10-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend15', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdb',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
