# Generated by Django 3.1.1 on 2021-02-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend24', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdb',
            name='comments',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
