# Generated by Django 3.1.1 on 2020-09-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatreUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('login_users', models.CharField(blank=True, max_length=30, null=True)),
                ('paass_users', models.CharField(blank=True, max_length=130, null=True)),
            ],
            options={
                'db_table': 'createuser',
                'ordering': ('id',),
            },
        ),
    ]
